baseURL = "https://daosyn.info/"
languageCode = "en-us"
title = "(daosyn)"
theme = "hugo-coder"

[params]
    author = "Brandon Dao"
    info = "Software Developer"
    description = "yak shaving"
    tags = "nothing"
    avatarurl = "/image/me.jpg"

    favicon_32 = "favicon.png"
    favicon_16 = "favicon.png"

    hidecredits = true
    hidecopyright = true
    inverted = true
    math = true

[[params.social]]
    name = "GitHub"
    icon = "fab fa-github-alt"
    url = "https://github.com/daosyn/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin-in"
    url = "https://linkedin.com/in/daosyn/"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase"
    url = "https://keybase.io/daosyn"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    url = "https://twitter.com/daosyn/"
[[params.social]]
    name = "Reddit"
    icon = "fab fa-reddit-alien"
    url = "https://reddit.com/user/daosyndrome"
[[params.social]]
    name = "Last.fm"
    icon = "fab fa-lastfm"
    url = "https://www.last.fm/user/daosyndrome"
    
# Menu links
[[menu.main]]
    name = "blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "about"
    weight = 2
    url  = "/about/"
